package net.explorercat.tasks;

import net.explorercat.cql.result.Result;
import net.explorercat.cql.result.ResultHeader;

/**
 * Interface for tasks in charge of processing the data requested by an API
 * call. These classes play the role of processing plug-ins on the server side
 * of ExplorerCat.
 * 
 * @author Jacob Almagro Garcia - jg10@sanger.ac.uk
 * @date 12 Jan 2011
 */

public interface ProcessingTask
{
    /**
     * Processes the result data passed as a parameter.
     * 
     * @param data Input/Output parameter that contains the data to be
     *        processed. Notice that passed object will be updated by the
     *        method.
     * 
     * @throws ProcessingTaskException If there is an error accessing or
     *         processing the data.
     */

    public Result processData(Result data) throws ProcessingTaskException;

    /**
     * Transforms the original headers to fit the output generated by the task.
     * The header indicates the label of the result, the columns (including
     * type) and the number of rows.
     * 
     * @param header Original header received by the task (coherent with the
     *        original data).
     * @return A new header that is coherent with the task data output.
     */

    public ResultHeader transformHeaders(ResultHeader header);
}
